services:
  hadoop:
    image: hadoop_i
    container_name: hadoop
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9870:9870"
      - "9864:9864"
      - "8088:8088"
      - "8042:8042"
      - "19888:19888"